services: 
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlzivafit
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@23"
    ports: 
      - "1433:1433"
