import { Injectable } from '@angular/core';

import { ProductCatalogItem, ProductCategory } from '../_models/product-catalog';

@Injectable({
  providedIn: 'root'
})
export class ProductCatalogService {
  private readonly apparelSizes = ['XS', 'S', 'M', 'L', 'XL', '2XL'];
  private readonly flexibleSizes = ['S', 'M', 'L', 'XL', '2XL'];
  private readonly accessorySizes = ['One Size'];

  private readonly products: ProductCatalogItem[] = [
    {
      id: 101,
      name: 'Sculpt High-Waist Legging',
      category: 'Leggings',
      fitType: 'High Waist',
      price: 899,
      priceText: 'R899',
      colour: 'Black',
      imageUrl: 'assets/leggings1.png',
      imageAlt: 'Black sculpt high-waist ZivaFit leggings',
      badge: 'Best Seller',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 1
    },
    {
      id: 102,
      name: 'Contour Pocket Legging',
      category: 'Leggings',
      fitType: 'Pocket',
      price: 949,
      priceText: 'R949',
      colour: 'Deep Cocoa',
      imageUrl: 'assets/leggings2.png',
      imageAlt: 'Deep cocoa ZivaFit pocket leggings',
      badge: 'Pocket Fit',
      sizes: this.flexibleSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 2
    },
    {
      id: 103,
      name: 'Espresso Core Legging',
      category: 'Leggings',
      fitType: 'High Waist',
      price: 849,
      priceText: 'R849',
      colour: 'Espresso',
      imageUrl: 'assets/leggings3.png',
      imageAlt: 'Espresso ZivaFit high-waist leggings',
      badge: 'Core Fit',
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 3
    },
    {
      id: 104,
      name: 'Olive Move Legging',
      category: 'Leggings',
      fitType: 'High Waist',
      price: 899,
      priceText: 'R899',
      colour: 'Olive',
      imageUrl: 'assets/leggings4.png',
      imageAlt: 'Olive ZivaFit activewear leggings',
      badge: 'Gym Ready',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 4
    },
    {
      id: 105,
      name: 'Cream Align Legging',
      category: 'Leggings',
      fitType: 'Seamless',
      price: 899,
      priceText: 'R899',
      colour: 'Cream',
      imageUrl: 'assets/leggings5.png',
      imageAlt: 'Cream seamless ZivaFit leggings',
      badge: 'Seamless',
      sizes: this.flexibleSizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 5
    },
    {
      id: 106,
      name: 'Cocoa Compression Legging',
      category: 'Leggings',
      fitType: 'Seamless',
      price: 999,
      priceText: 'R999',
      colour: 'Cocoa',
      imageUrl: 'assets/leggings6.png',
      imageAlt: 'Cocoa compression ZivaFit leggings',
      badge: 'Compression',
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 6
    },
    {
      id: 107,
      name: 'Auburn Flex Legging',
      category: 'Leggings',
      fitType: 'High Waist',
      price: 799,
      priceText: 'R799',
      colour: 'Auburn',
      imageUrl: 'assets/leggings8.png',
      imageAlt: 'Auburn ZivaFit flexible leggings',
      badge: 'Everyday Fit',
      sizes: this.flexibleSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 7
    },
    {
      id: 108,
      name: 'Brown Pocket Legging',
      category: 'Leggings',
      fitType: 'Pocket',
      price: 899,
      priceText: 'R899',
      colour: 'Brown',
      imageUrl: 'assets/leggings9.png',
      imageAlt: 'Brown pocket ZivaFit leggings',
      badge: 'Pocket Fit',
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 8
    },
    {
      id: 109,
      name: 'Studio Stretch Legging',
      category: 'Leggings',
      fitType: 'High Waist',
      price: 849,
      priceText: 'R849',
      colour: 'Warm Taupe',
      imageUrl: 'assets/leggings10.png',
      imageAlt: 'Warm taupe ZivaFit stretch leggings',
      badge: 'Studio Fit',
      sizes: this.flexibleSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 9
    },
    {
      id: 110,
      name: 'Everyday Black Bootleg',
      category: 'Leggings',
      fitType: 'Bootleg',
      price: 899,
      priceText: 'R899',
      colour: 'Black',
      imageUrl: 'assets/bootlegleggings1.png',
      imageAlt: 'Black ZivaFit bootleg leggings',
      badge: 'Bootleg',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 10
    },
    {
      id: 111,
      name: 'Mocha Bootleg Legging',
      category: 'Leggings',
      fitType: 'Bootleg',
      price: 949,
      priceText: 'R949',
      colour: 'Mocha',
      imageUrl: 'assets/bootlegleggings2.png',
      imageAlt: 'Mocha ZivaFit bootleg leggings',
      badge: 'Soft Flare',
      sizes: this.flexibleSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 11
    },
    {
      id: 112,
      name: 'Sculpt Flare Bootleg',
      category: 'Leggings',
      fitType: 'Bootleg',
      price: 999,
      priceText: 'R999',
      colour: 'Chocolate',
      imageUrl: 'assets/bootlegleggings3.png',
      imageAlt: 'Chocolate ZivaFit sculpt flare bootleg leggings',
      badge: 'Flare Fit',
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 12
    },

    {
      id: 201,
      name: 'Power Support Sports Bra',
      category: 'Sports Bras',
      fitType: 'High Support',
      price: 699,
      priceText: 'R699',
      colour: 'Black',
      imageUrl: 'assets/bra5.png',
      imageAlt: 'Black power support ZivaFit sports bra',
      badge: 'Supportive Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 1
    },
    {
      id: 202,
      name: 'Cocoa Sculpt Sports Bra',
      category: 'Sports Bras',
      fitType: 'Medium Support',
      price: 649,
      priceText: 'R649',
      colour: 'Cocoa',
      imageUrl: 'assets/bra1.png',
      imageAlt: 'Cocoa ZivaFit sculpt sports bra',
      badge: 'New Colour',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 2
    },
    {
      id: 203,
      name: 'Cream Align Sports Bra',
      category: 'Sports Bras',
      fitType: 'Light Support',
      price: 599,
      priceText: 'R599',
      colour: 'Cream',
      imageUrl: 'assets/bra2.png',
      imageAlt: 'Cream ZivaFit align sports bra',
      badge: 'Soft Feel',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 3
    },
    {
      id: 204,
      name: 'Olive Train Sports Bra',
      category: 'Sports Bras',
      fitType: 'High Support',
      price: 699,
      priceText: 'R699',
      colour: 'Olive',
      imageUrl: 'assets/bra3.png',
      imageAlt: 'Olive ZivaFit training sports bra',
      badge: 'Gym Ready',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 4
    },
    {
      id: 205,
      name: 'Mocha Soft Move Bra',
      category: 'Sports Bras',
      fitType: 'Light Support',
      price: 549,
      priceText: 'R549',
      colour: 'Mocha',
      imageUrl: 'assets/bra4.png',
      imageAlt: 'Mocha ZivaFit soft move sports bra',
      badge: 'Everyday Fit',
      sizes: this.flexibleSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 5
    },
    {
      id: 206,
      name: 'Seamless Core Bra',
      category: 'Sports Bras',
      fitType: 'Medium Support',
      price: 649,
      priceText: 'R649',
      colour: 'Charcoal',
      imageUrl: 'assets/bra5.png',
      imageAlt: 'Charcoal ZivaFit seamless core sports bra',
      badge: 'Seamless',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 6
    },
    {
      id: 207,
      name: 'Espresso Racerback Bra',
      category: 'Sports Bras',
      fitType: 'High Support',
      price: 699,
      priceText: 'R699',
      colour: 'Espresso',
      imageUrl: 'assets/bra1.png',
      imageAlt: 'Espresso ZivaFit racerback sports bra',
      badge: 'Secure Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 7
    },
    {
      id: 208,
      name: 'Taupe Studio Bra',
      category: 'Sports Bras',
      fitType: 'Medium Support',
      price: 599,
      priceText: 'R599',
      colour: 'Warm Taupe',
      imageUrl: 'assets/bra2.png',
      imageAlt: 'Warm taupe ZivaFit studio sports bra',
      badge: 'Studio Fit',
      sizes: this.flexibleSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 8
    },
    {
      id: 209,
      name: 'Brown Everyday Bra',
      category: 'Sports Bras',
      fitType: 'Medium Support',
      price: 649,
      priceText: 'R649',
      colour: 'Brown',
      imageUrl: 'assets/bra3.png',
      imageAlt: 'Brown ZivaFit everyday sports bra',
      badge: 'Core Fit',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 9
    },
    {
      id: 210,
      name: 'Black Strappy Bra',
      category: 'Sports Bras',
      fitType: 'Light Support',
      price: 579,
      priceText: 'R579',
      colour: 'Black',
      imageUrl: 'assets/bra4.png',
      imageAlt: 'Black ZivaFit strappy sports bra',
      badge: 'Strappy Fit',
      sizes: this.flexibleSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 10
    },
    {
      id: 211,
      name: 'Cream Longline Bra',
      category: 'Sports Bras',
      fitType: 'High Support',
      price: 729,
      priceText: 'R729',
      colour: 'Cream',
      imageUrl: 'assets/bra5.png',
      imageAlt: 'Cream ZivaFit longline sports bra',
      badge: 'Longline',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 11
    },
    {
      id: 212,
      name: 'Mocha Flex Bra',
      category: 'Sports Bras',
      fitType: 'Medium Support',
      price: 629,
      priceText: 'R629',
      colour: 'Mocha',
      imageUrl: 'assets/bra1.png',
      imageAlt: 'Mocha ZivaFit flex sports bra',
      badge: 'Flexible Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 12
    },

    {
      id: 301,
      name: 'Everyday Long Sleeve Top',
      category: 'Tops',
      fitType: 'Long Sleeve',
      price: 749,
      priceText: 'R749',
      colour: 'Cocoa',
      imageUrl: 'assets/longsleeveshirt3.png',
      imageAlt: 'Cocoa ZivaFit everyday long sleeve activewear top',
      badge: 'Best Seller',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 1
    },
    {
      id: 302,
      name: 'Cream Fitted Long Sleeve',
      category: 'Tops',
      fitType: 'Long Sleeve',
      price: 699,
      priceText: 'R699',
      colour: 'Cream',
      imageUrl: 'assets/longsleeveshirt1.png',
      imageAlt: 'Cream ZivaFit fitted long sleeve activewear top',
      badge: 'New Colour',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 2
    },
    {
      id: 303,
      name: 'Cocoa Wrap Long Sleeve',
      category: 'Tops',
      fitType: 'Long Sleeve',
      price: 729,
      priceText: 'R729',
      colour: 'Cocoa',
      imageUrl: 'assets/longsleeveshirt2.png',
      imageAlt: 'Cocoa ZivaFit wrap long sleeve gym top',
      badge: 'Layering Fit',
      sizes: this.flexibleSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 3
    },
    {
      id: 304,
      name: 'Black Short Sleeve Training Top',
      category: 'Tops',
      fitType: 'Short Sleeve',
      price: 549,
      priceText: 'R549',
      colour: 'Black',
      imageUrl: 'assets/shortsleeveshirt1.png',
      imageAlt: 'Black ZivaFit short sleeve training top',
      badge: 'Gym Ready',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 4
    },
    {
      id: 305,
      name: 'Brown Everyday Tee',
      category: 'Tops',
      fitType: 'Short Sleeve',
      price: 499,
      priceText: 'R499',
      colour: 'Brown',
      imageUrl: 'assets/shortsleeveshirt2.png',
      imageAlt: 'Brown ZivaFit everyday short sleeve top',
      badge: 'Everyday Fit',
      sizes: this.flexibleSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 5
    },
    {
      id: 306,
      name: 'Olive Long Sleeve Top',
      category: 'Tops',
      fitType: 'Long Sleeve',
      price: 699,
      priceText: 'R699',
      colour: 'Olive',
      imageUrl: 'assets/longsleeveshirt1.png',
      imageAlt: 'Olive ZivaFit long sleeve activewear top',
      badge: 'Soft Stretch',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 6
    },
    {
      id: 307,
      name: 'Espresso Crop Tee',
      category: 'Tops',
      fitType: 'Short Sleeve',
      price: 529,
      priceText: 'R529',
      colour: 'Espresso',
      imageUrl: 'assets/shortsleeveshirt1.png',
      imageAlt: 'Espresso ZivaFit crop tee activewear top',
      badge: 'Cropped Fit',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 7
    },
    {
      id: 308,
      name: 'Taupe Relaxed Top',
      category: 'Tops',
      fitType: 'Short Sleeve',
      price: 499,
      priceText: 'R499',
      colour: 'Warm Taupe',
      imageUrl: 'assets/shortsleeveshirt2.png',
      imageAlt: 'Warm taupe ZivaFit relaxed activewear top',
      badge: 'Relaxed Fit',
      sizes: this.flexibleSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 8
    },
    {
      id: 309,
      name: 'Cream Ribbed Vest',
      category: 'Tops',
      fitType: 'Vest',
      price: 449,
      priceText: 'R449',
      colour: 'Cream',
      imageUrl: 'assets/shortsleeveshirt2.png',
      imageAlt: 'Cream ZivaFit ribbed vest activewear top',
      badge: 'Ribbed Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 9
    },
    {
      id: 310,
      name: 'Mocha Zip Long Sleeve',
      category: 'Tops',
      fitType: 'Long Sleeve',
      price: 799,
      priceText: 'R799',
      colour: 'Mocha',
      imageUrl: 'assets/longsleeveshirt3.png',
      imageAlt: 'Mocha ZivaFit zip long sleeve activewear top',
      badge: 'Premium Layer',
      sizes: this.flexibleSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 10
    },
    {
      id: 311,
      name: 'Black Fitted Vest',
      category: 'Tops',
      fitType: 'Vest',
      price: 449,
      priceText: 'R449',
      colour: 'Black',
      imageUrl: 'assets/shortsleeveshirt1.png',
      imageAlt: 'Black ZivaFit fitted vest activewear top',
      badge: 'Core Basic',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 11
    },
    {
      id: 312,
      name: 'Auburn Studio Top',
      category: 'Tops',
      fitType: 'Long Sleeve',
      price: 699,
      priceText: 'R699',
      colour: 'Auburn',
      imageUrl: 'assets/longsleeveshirt1.png',
      imageAlt: 'Auburn ZivaFit studio long sleeve activewear top',
      badge: 'Studio Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 12
    },

    {
      id: 401,
      name: 'Studio Matching Set',
      category: 'Sets',
      fitType: 'Matching Set',
      price: 1200,
      priceText: 'R1 200',
      colour: 'Cocoa',
      imageUrl: 'assets/sets5.png',
      imageAlt: 'Cocoa ZivaFit studio matching activewear set',
      badge: 'Full Look',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 1
    },
    {
      id: 402,
      name: 'Cream Align Set',
      category: 'Sets',
      fitType: 'Matching Set',
      price: 1150,
      priceText: 'R1 150',
      colour: 'Cream',
      imageUrl: 'assets/sets1.png',
      imageAlt: 'Cream ZivaFit align matching activewear set',
      badge: 'New Set',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 2
    },
    {
      id: 403,
      name: 'Cocoa Sculpt Set',
      category: 'Sets',
      fitType: 'Compression Set',
      price: 1250,
      priceText: 'R1 250',
      colour: 'Cocoa',
      imageUrl: 'assets/sets2.png',
      imageAlt: 'Cocoa ZivaFit sculpt activewear set',
      badge: 'Sculpt Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 3
    },
    {
      id: 404,
      name: 'Olive Move Set',
      category: 'Sets',
      fitType: 'Training Set',
      price: 1199,
      priceText: 'R1 199',
      colour: 'Olive',
      imageUrl: 'assets/sets3.png',
      imageAlt: 'Olive ZivaFit move activewear set',
      badge: 'Gym Ready',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 4
    },
    {
      id: 405,
      name: 'Black Core Set',
      category: 'Sets',
      fitType: 'Training Set',
      price: 1150,
      priceText: 'R1 150',
      colour: 'Black',
      imageUrl: 'assets/sets4.png',
      imageAlt: 'Black ZivaFit core activewear set',
      badge: 'Core Set',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 5
    },
    {
      id: 406,
      name: 'Espresso Seamless Set',
      category: 'Sets',
      fitType: 'Seamless Set',
      price: 1299,
      priceText: 'R1 299',
      colour: 'Espresso',
      imageUrl: 'assets/sets5.png',
      imageAlt: 'Espresso ZivaFit seamless activewear set',
      badge: 'Seamless',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 6
    },
    {
      id: 407,
      name: 'Mocha Studio Set',
      category: 'Sets',
      fitType: 'Matching Set',
      price: 1200,
      priceText: 'R1 200',
      colour: 'Mocha',
      imageUrl: 'assets/sets1.png',
      imageAlt: 'Mocha ZivaFit studio matching set',
      badge: 'Studio Fit',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 7
    },
    {
      id: 408,
      name: 'Taupe Training Set',
      category: 'Sets',
      fitType: 'Training Set',
      price: 1175,
      priceText: 'R1 175',
      colour: 'Warm Taupe',
      imageUrl: 'assets/sets2.png',
      imageAlt: 'Warm taupe ZivaFit training activewear set',
      badge: 'Training Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 8
    },
    {
      id: 409,
      name: 'Brown Everyday Set',
      category: 'Sets',
      fitType: 'Matching Set',
      price: 1099,
      priceText: 'R1 099',
      colour: 'Brown',
      imageUrl: 'assets/sets3.png',
      imageAlt: 'Brown ZivaFit everyday activewear set',
      badge: 'Everyday Set',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 9
    },
    {
      id: 410,
      name: 'Cream Longline Set',
      category: 'Sets',
      fitType: 'Compression Set',
      price: 1299,
      priceText: 'R1 299',
      colour: 'Cream',
      imageUrl: 'assets/sets4.png',
      imageAlt: 'Cream ZivaFit longline activewear set',
      badge: 'Premium Fit',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 10
    },
    {
      id: 411,
      name: 'Auburn Flow Set',
      category: 'Sets',
      fitType: 'Seamless Set',
      price: 1199,
      priceText: 'R1 199',
      colour: 'Auburn',
      imageUrl: 'assets/sets5.png',
      imageAlt: 'Auburn ZivaFit flow activewear set',
      badge: 'Flow Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 11
    },
    {
      id: 412,
      name: 'Black Power Set',
      category: 'Sets',
      fitType: 'Compression Set',
      price: 1350,
      priceText: 'R1 350',
      colour: 'Black',
      imageUrl: 'assets/sets1.png',
      imageAlt: 'Black ZivaFit power activewear set',
      badge: 'Power Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 12
    },

    {
      id: 501,
      name: 'Move Pocket Short',
      category: 'Shorts',
      fitType: 'Shorts',
      price: 499,
      priceText: 'R499',
      colour: 'Black',
      imageUrl: 'assets/short3.png',
      imageAlt: 'Black ZivaFit move pocket activewear shorts',
      badge: 'Easy Movement',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 1
    },
    {
      id: 502,
      name: 'Cream Bike Short',
      category: 'Shorts',
      fitType: 'Bike Shorts',
      price: 549,
      priceText: 'R549',
      colour: 'Cream',
      imageUrl: 'assets/short1.png',
      imageAlt: 'Cream ZivaFit bike shorts',
      badge: 'New Colour',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 2
    },
    {
      id: 503,
      name: 'Cocoa Training Short',
      category: 'Shorts',
      fitType: 'Shorts',
      price: 499,
      priceText: 'R499',
      colour: 'Cocoa',
      imageUrl: 'assets/short2.png',
      imageAlt: 'Cocoa ZivaFit training shorts',
      badge: 'Gym Ready',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 3
    },
    {
      id: 504,
      name: 'Olive Gym Short',
      category: 'Shorts',
      fitType: 'Shorts',
      price: 529,
      priceText: 'R529',
      colour: 'Olive',
      imageUrl: 'assets/short1.png',
      imageAlt: 'Olive ZivaFit gym shorts',
      badge: 'Training Fit',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 4
    },
    {
      id: 505,
      name: 'Black Core Short',
      category: 'Shorts',
      fitType: 'Bike Shorts',
      price: 499,
      priceText: 'R499',
      colour: 'Black',
      imageUrl: 'assets/short2.png',
      imageAlt: 'Black ZivaFit core bike shorts',
      badge: 'Core Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 5
    },
    {
      id: 506,
      name: 'Brown Everyday Short',
      category: 'Shorts',
      fitType: 'Shorts',
      price: 479,
      priceText: 'R479',
      colour: 'Brown',
      imageUrl: 'assets/short3.png',
      imageAlt: 'Brown ZivaFit everyday shorts',
      badge: 'Everyday Fit',
      sizes: this.flexibleSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 6
    },
    {
      id: 507,
      name: 'Cream Active Skort',
      category: 'Shorts',
      fitType: 'Skort',
      price: 599,
      priceText: 'R599',
      colour: 'Cream',
      imageUrl: 'assets/skort1.png',
      imageAlt: 'Cream ZivaFit activewear skort',
      badge: 'Skort Fit',
      sizes: this.apparelSizes,
      isNew: true,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 7
    },
    {
      id: 508,
      name: 'Cocoa Studio Skort',
      category: 'Shorts',
      fitType: 'Skort',
      price: 649,
      priceText: 'R649',
      colour: 'Cocoa',
      imageUrl: 'assets/skort2.png',
      imageAlt: 'Cocoa ZivaFit studio skort',
      badge: 'Studio Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 8
    },
    {
      id: 509,
      name: 'Black Pocket Skort',
      category: 'Shorts',
      fitType: 'Skort',
      price: 629,
      priceText: 'R629',
      colour: 'Black',
      imageUrl: 'assets/skort1.png',
      imageAlt: 'Black ZivaFit pocket skort',
      badge: 'Pocket Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 9
    },
    {
      id: 510,
      name: 'Taupe Studio Short',
      category: 'Shorts',
      fitType: 'Shorts',
      price: 529,
      priceText: 'R529',
      colour: 'Warm Taupe',
      imageUrl: 'assets/short1.png',
      imageAlt: 'Warm taupe ZivaFit studio shorts',
      badge: 'Studio Fit',
      sizes: this.flexibleSizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 10
    },
    {
      id: 511,
      name: 'Auburn Active Short',
      category: 'Shorts',
      fitType: 'Bike Shorts',
      price: 549,
      priceText: 'R549',
      colour: 'Auburn',
      imageUrl: 'assets/short2.png',
      imageAlt: 'Auburn ZivaFit active bike shorts',
      badge: 'Active Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 11
    },
    {
      id: 512,
      name: 'Mocha Move Skort',
      category: 'Shorts',
      fitType: 'Skort',
      price: 649,
      priceText: 'R649',
      colour: 'Mocha',
      imageUrl: 'assets/skort2.png',
      imageAlt: 'Mocha ZivaFit move skort',
      badge: 'Move Fit',
      sizes: this.apparelSizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 12
    },

    {
      id: 601,
      name: 'ZivaFit Everyday Gym Bag',
      category: 'Accessories',
      fitType: 'Gym Bag',
      price: 849,
      priceText: 'R849',
      colour: 'Black',
      imageUrl: 'assets/gymbag5.png',
      imageAlt: 'Black ZivaFit everyday gym bag',
      badge: 'Carry All',
      sizes: this.accessorySizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 1
    },
    {
      id: 602,
      name: 'Compact Duffel Bag',
      category: 'Accessories',
      fitType: 'Gym Bag',
      price: 699,
      priceText: 'R699',
      colour: 'Cocoa',
      imageUrl: 'assets/gymbag1.png',
      imageAlt: 'Cocoa ZivaFit compact duffel gym bag',
      badge: 'New Drop',
      sizes: this.accessorySizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 2
    },
    {
      id: 603,
      name: 'Cocoa Training Tote',
      category: 'Accessories',
      fitType: 'Tote Bag',
      price: 599,
      priceText: 'R599',
      colour: 'Cocoa',
      imageUrl: 'assets/gymbag2.png',
      imageAlt: 'Cocoa ZivaFit training tote bag',
      badge: 'Training Tote',
      sizes: this.accessorySizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 3
    },
    {
      id: 604,
      name: 'Studio Duffle Bag',
      category: 'Accessories',
      fitType: 'Gym Bag',
      price: 799,
      priceText: 'R799',
      colour: 'Cream',
      imageUrl: 'assets/gymbag3.png',
      imageAlt: 'Cream ZivaFit studio duffle gym bag',
      badge: 'Studio Ready',
      sizes: this.accessorySizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 4
    },
    {
      id: 605,
      name: 'Cream Carry Bag',
      category: 'Accessories',
      fitType: 'Tote Bag',
      price: 649,
      priceText: 'R649',
      colour: 'Cream',
      imageUrl: 'assets/gymbag4.png',
      imageAlt: 'Cream ZivaFit carry tote bag',
      badge: 'Everyday Carry',
      sizes: this.accessorySizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 5
    },
    {
      id: 606,
      name: 'Black Weekender Gym Bag',
      category: 'Accessories',
      fitType: 'Travel Bag',
      price: 899,
      priceText: 'R899',
      colour: 'Black',
      imageUrl: 'assets/gymbag5.png',
      imageAlt: 'Black ZivaFit weekender gym bag',
      badge: 'Weekend Ready',
      sizes: this.accessorySizes,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
      isActive: true,
      displayOrder: 6
    },
    {
      id: 607,
      name: 'Mocha Yoga Bag',
      category: 'Accessories',
      fitType: 'Yoga Bag',
      price: 549,
      priceText: 'R549',
      colour: 'Mocha',
      imageUrl: 'assets/gymbag1.png',
      imageAlt: 'Mocha ZivaFit yoga bag',
      badge: 'Yoga Ready',
      sizes: this.accessorySizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 7
    },
    {
      id: 608,
      name: 'Olive Fitness Tote',
      category: 'Accessories',
      fitType: 'Tote Bag',
      price: 599,
      priceText: 'R599',
      colour: 'Olive',
      imageUrl: 'assets/gymbag2.png',
      imageAlt: 'Olive ZivaFit fitness tote bag',
      badge: 'Fitness Tote',
      sizes: this.accessorySizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 8
    },
    {
      id: 609,
      name: 'Taupe Travel Gym Bag',
      category: 'Accessories',
      fitType: 'Travel Bag',
      price: 899,
      priceText: 'R899',
      colour: 'Warm Taupe',
      imageUrl: 'assets/gymbag3.png',
      imageAlt: 'Warm taupe ZivaFit travel gym bag',
      badge: 'Travel Fit',
      sizes: this.accessorySizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 9
    },
    {
      id: 610,
      name: 'Small Essentials Bag',
      category: 'Accessories',
      fitType: 'Essentials Bag',
      price: 399,
      priceText: 'R399',
      colour: 'Black',
      imageUrl: 'assets/gymbag4.png',
      imageAlt: 'Black ZivaFit small essentials bag',
      badge: 'Essentials',
      sizes: this.accessorySizes,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
      isActive: true,
      displayOrder: 10
    },
    {
      id: 611,
      name: 'Brown Everyday Duffel',
      category: 'Accessories',
      fitType: 'Gym Bag',
      price: 749,
      priceText: 'R749',
      colour: 'Brown',
      imageUrl: 'assets/gymbag5.png',
      imageAlt: 'Brown ZivaFit everyday duffel bag',
      badge: 'Duffel Fit',
      sizes: this.accessorySizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 11
    },
    {
      id: 612,
      name: 'Cream Wellness Tote',
      category: 'Accessories',
      fitType: 'Tote Bag',
      price: 599,
      priceText: 'R599',
      colour: 'Cream',
      imageUrl: 'assets/gymbag2.png',
      imageAlt: 'Cream ZivaFit wellness tote bag',
      badge: 'Wellness Carry',
      sizes: this.accessorySizes,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
      isActive: true,
      displayOrder: 12
    }
  ];

  getProducts(): ProductCatalogItem[] {
    return this.products
      .filter(product => product.isActive)
      .map(product => ({
        ...product,
        sizes: [...product.sizes]
      }));
  }

  getProductsByCategory(category: ProductCategory): ProductCatalogItem[] {
    return this.getProducts().filter(product => product.category === category);
  }

  getNewProducts(): ProductCatalogItem[] {
    return this.getProducts().filter(product => product.isNew);
  }
}